name: build

permissions:
  contents: read

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build - arm64v8
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.90"
          override: true
          default: true
          components: rustfmt
          profile: minimal
          target: aarch64-unknown-linux-musl

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=aarch64-unknown-linux-musl
          use-cross: true

      - name: Exec chmod
        run: chmod -v a+x target/aarch64-unknown-linux-musl/release/*

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-arm64v8
          path: |
            target/aarch64-unknown-linux-musl/release/hbbr
            target/aarch64-unknown-linux-musl/release/hbbs
            target/aarch64-unknown-linux-musl/release/rustdesk-utils
          if-no-files-found: error
